include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    library_private_types_in_public_api: false
    avoid_dynamic_calls: false

