name: raygun4flutter
description: Raygun4flutter package is the official Raygun crash reporting provider for Flutter.
version: 0.5.1
homepage: https://raygun.com
repository: https://github.com/MindscapeHQ/Raygun4Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.raygun.raygun4flutter.raygun4flutter
        pluginClass: Raygun4flutterPlugin
      ios:
        pluginClass: Raygun4flutterPlugin
