name: raygun
description: Flutter crash reporting provider for Raygun.
version: 0.0.3
homepage: https://raygun.com
repository: https://github.com/MindscapeHQ/Raygun4Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ^1.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.raygun.raygun4flutter.raygun4flutter
        pluginClass: Raygun4flutterPlugin
      ios:
        pluginClass: Raygun4flutterPlugin


