name: raygun4flutter
description: Raygun4flutter package is the official Raygun crash reporting provider for Flutter.
version: 1.0.0-dev.2
homepage: https://raygun.com
repository: https://github.com/MindscapeHQ/Raygun4Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  connectivity_plus: ^1.4.0
  device_info_plus: ^2.1.0
  flutter:
    sdk: flutter

  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.1.0
  network_info_plus: ^1.1.0
  package_info_plus: ^1.0.6
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8
  stack_trace: ^1.10.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter

  json_serializable: ^5.0.1

  lint: ^1.5.3

flutter:
