name: raygun4flutter
description: Raygun4flutter package is the official Raygun crash reporting provider for Flutter.
version: 2.0.0
homepage: https://raygun.com
repository: https://github.com/MindscapeHQ/Raygun4Flutter

environment:
  sdk: "^3.0.0"
  flutter: ">=1.12.0"

dependencies:
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.0.1
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.1.0
  network_info_plus: ^4.0.1
  package_info_plus: ^4.0.1
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8
  stack_trace: ^1.11.0
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.1

  lint: ">=1.7.2 <3.0.0"

flutter:
