name: raygun4flutter
description: Raygun4flutter package is the official Raygun crash reporting provider for Flutter.
version: 0.5.1
homepage: https://raygun.com
repository: https://github.com/MindscapeHQ/Raygun4Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  json_annotation: ^4.1.0
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^5.0.1

  lint: ^1.5.3

  build_runner: ^2.1.2
flutter:
